/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import DTOS.GuardarClienteDTO;
import Negocio.IClienteNegocio;
import Negocio.NegocioException;
import Utilidades.PanelManager;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.ZoneId;
import javax.swing.JOptionPane;


/**
 *
 * @author gaspa
 */
public class RegistrarClientePanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarClientePanel
     */
    private final IClienteNegocio clienteNegocio;
    private final PanelManager panel;
    public RegistrarClientePanel(IClienteNegocio clienteNegocio, PanelManager panel) {
        initComponents();
        this.clienteNegocio=clienteNegocio;
        this.panel=panel;
    }
    public void registrarCliente() {
        LocalDate fechaNacimiento = fechaNacimientoPanel.getSelectedDate();
        Date fechaNacimientoDate = (fechaNacimiento != null) 
                ? Date.from(fechaNacimiento.atStartOfDay(ZoneId.systemDefault()).toInstant()) 
                : null;

        GuardarClienteDTO guardar = new GuardarClienteDTO(
                jTextFieldNombresCliente.getText(),
                jTextFieldApellidoPaternoCliente.getText(),
                jTextFieldApellidoMaternoCliente.getText(),
                fechaNacimientoDate
        );

        try {
            clienteNegocio.guardar(guardar);
            JOptionPane.showMessageDialog(null, "Cliente registrado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(null, "Error al registrar cliente: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGrande = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabellogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombreClientes = new javax.swing.JLabel();
        jLabelApellidoPaternoCliente = new javax.swing.JLabel();
        jLabelApellidoMaternoCliente = new javax.swing.JLabel();
        jButtonCancelarRegistroCliente = new javax.swing.JButton();
        jButtonRegistrarCliente = new javax.swing.JButton();
        jTextFieldNombresCliente = new javax.swing.JTextField();
        jTextFieldApellidoPaternoCliente = new javax.swing.JTextField();
        jTextFieldApellidoMaternoCliente = new javax.swing.JTextField();
        jLabelFechaNacimientoCliente1 = new javax.swing.JLabel();
        fechaNacimientoPanel = new com.github.lgooddatepicker.components.CalendarPanel();

        setMaximumSize(new java.awt.Dimension(1385, 897));
        setMinimumSize(new java.awt.Dimension(1385, 897));
        setPreferredSize(new java.awt.Dimension(1385, 897));

        jPanelGrande.setBackground(new java.awt.Color(102, 204, 255));
        jPanelGrande.setMaximumSize(new java.awt.Dimension(1385, 897));
        jPanelGrande.setMinimumSize(new java.awt.Dimension(1385, 897));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 60)); // NOI18N
        jLabel1.setText("Registrar Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabellogo, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(452, 452, 452))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabellogo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelNombreClientes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelNombreClientes.setText("Nombres:");

        jLabelApellidoPaternoCliente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelApellidoPaternoCliente.setText("Apellido Paterno:");

        jLabelApellidoMaternoCliente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelApellidoMaternoCliente.setText("Apellido Materno:");

        jButtonCancelarRegistroCliente.setBackground(new java.awt.Color(255, 102, 51));
        jButtonCancelarRegistroCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelarRegistroCliente.setText("Cancelar");
        jButtonCancelarRegistroCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancelarRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarRegistroClienteActionPerformed(evt);
            }
        });

        jButtonRegistrarCliente.setBackground(new java.awt.Color(51, 153, 0));
        jButtonRegistrarCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRegistrarCliente.setText("Registrar");
        jButtonRegistrarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarClienteActionPerformed(evt);
            }
        });

        jTextFieldNombresCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombresClienteActionPerformed(evt);
            }
        });

        jTextFieldApellidoPaternoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoPaternoClienteActionPerformed(evt);
            }
        });

        jTextFieldApellidoMaternoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoMaternoClienteActionPerformed(evt);
            }
        });

        jLabelFechaNacimientoCliente1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelFechaNacimientoCliente1.setText("Fecha de Nacimiento:");

        javax.swing.GroupLayout jPanelGrandeLayout = new javax.swing.GroupLayout(jPanelGrande);
        jPanelGrande.setLayout(jPanelGrandeLayout);
        jPanelGrandeLayout.setHorizontalGroup(
            jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelGrandeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonCancelarRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelGrandeLayout.createSequentialGroup()
                .addGroup(jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGrandeLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombreClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombresCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellidoMaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelGrandeLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabelApellidoMaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellidoPaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidoPaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaNacimientoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaNacimientoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        jPanelGrandeLayout.setVerticalGroup(
            jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrandeLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellidoPaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombresCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jTextFieldApellidoPaternoCliente))
                .addGroup(jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGrandeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jLabelApellidoMaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellidoMaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addGroup(jPanelGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelarRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(jPanelGrandeLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabelFechaNacimientoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaNacimientoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1385, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarRegistroClienteActionPerformed
        ListadoClientesPanel listaPanel = new ListadoClientesPanel(clienteNegocio, panel);
        panel.cambiarPanel(listaPanel);
    }//GEN-LAST:event_jButtonCancelarRegistroClienteActionPerformed

    private void jButtonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarClienteActionPerformed
        this.registrarCliente();
    }//GEN-LAST:event_jButtonRegistrarClienteActionPerformed

    private void jTextFieldNombresClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombresClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombresClienteActionPerformed

    private void jTextFieldApellidoPaternoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoPaternoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoPaternoClienteActionPerformed

    private void jTextFieldApellidoMaternoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoMaternoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoMaternoClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.CalendarPanel fechaNacimientoPanel;
    private javax.swing.JButton jButtonCancelarRegistroCliente;
    private javax.swing.JButton jButtonRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellidoMaternoCliente;
    private javax.swing.JLabel jLabelApellidoPaternoCliente;
    private javax.swing.JLabel jLabelFechaNacimientoCliente1;
    private javax.swing.JLabel jLabelNombreClientes;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGrande;
    private javax.swing.JTextField jTextFieldApellidoMaternoCliente;
    private javax.swing.JTextField jTextFieldApellidoPaternoCliente;
    private javax.swing.JTextField jTextFieldNombresCliente;
    // End of variables declaration//GEN-END:variables
}
