/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import DTOS.AnalisisDetalleDTO;
import DTOS.GuardarResultadoDTO;
import DTOS.ParametroDTO;
import DTOS.ParametroTablaDTO;
import DTOS.ResultadoParametroAnalisisTablaDTO;
import Negocio.IAnalisisNegocio;
import Negocio.IParametroNegocio;
import Negocio.IResultadoNegocio;
import Negocio.NegocioException;
import Utilidades.PanelManager;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ilian Fernando Gastelum Romo 228761
 */
public class ResultadosCapturaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResultadosCapturaPanel
     */
    private PanelManager panel;
    private IAnalisisNegocio analisisNegocio;
    private IResultadoNegocio resultadoNegocio;
    private int idAnalisis;
    private List<ParametroDTO> parametros;
    private List<ResultadoParametroAnalisisTablaDTO> resultados;
    private final IParametroNegocio parametroNegocio;

    public ResultadosCapturaPanel(PanelManager panel, IAnalisisNegocio analisisNegocio, int idAnalisis, 
                                  IResultadoNegocio resultadoNegocio, List<ParametroDTO> parametros, 
                                  List<ResultadoParametroAnalisisTablaDTO> resultados,IParametroNegocio parametroNegocio) {
        initComponents();
        this.panel = panel;
        this.analisisNegocio = analisisNegocio;
        this.idAnalisis = idAnalisis;
        this.resultadoNegocio = resultadoNegocio;
        this.parametros = parametros;
        this.resultados = resultados;
        this.parametroNegocio =parametroNegocio;
        cargarDatosTabla();
    }
    private void cargarDatosTabla() {
    DefaultTableModel modeloTabla = (DefaultTableModel) this.TablaResultados.getModel();
    modeloTabla.setRowCount(0);

    for (ParametroDTO parametro : parametros) {
        String resultadoValor = buscarResultado(parametro.getId());
        Object[] fila = new Object[]{
            parametro.getNombreParametro(),
            resultadoValor != null ? resultadoValor : ""
        };
        modeloTabla.addRow(fila);
    }
}

    private String buscarResultado(int idParametro) {
        for (ResultadoParametroAnalisisTablaDTO resultado : resultados) {
            if (resultado.getIdParametro() == idParametro) {
                return resultado.getResultado();
            }
        }
        return null;
    }

    private void guardarResultados() {
        try {
            DefaultTableModel modeloTabla = (DefaultTableModel) this.TablaResultados.getModel();

            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                String nombreParametro = (String) modeloTabla.getValueAt(i, 0);
                String valor = (String) modeloTabla.getValueAt(i, 1);

                int idParametro = obtenerIdParametro(nombreParametro);
                System.out.println(idAnalisis);

                resultadoNegocio.guardar(new GuardarResultadoDTO(idParametro, valor, new Date()));
            }

            JOptionPane.showMessageDialog(this, "Resultados guardados exitosamente.");
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los resultados: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private int obtenerIdParametro(String nombreParametro) throws NegocioException {
        for (ParametroDTO parametro : parametros) {
            if (parametro.getNombreParametro().equals(nombreParametro)) {
                return parametro.getId();
            }
        }
        throw new NegocioException("No se encontró el parámetro: " + nombreParametro);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        folioLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreClienteLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombrePruebaLabel = new javax.swing.JLabel();
        registrarBTN = new javax.swing.JButton();
        cancelarBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(1385, 897));
        setMinimumSize(new java.awt.Dimension(1385, 897));
        setPreferredSize(new java.awt.Dimension(1385, 897));

        TablaResultados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parametro", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(TablaResultados);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Capture los resultados");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Folio:");

        folioLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        folioLabel.setText("---");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cliente:");

        nombreClienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreClienteLabel.setText("---");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Prueba");

        nombrePruebaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombrePruebaLabel.setText("---");

        registrarBTN.setBackground(new java.awt.Color(51, 204, 0));
        registrarBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrarBTN.setText("Registrar");
        registrarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBTNActionPerformed(evt);
            }
        });

        cancelarBTN.setBackground(new java.awt.Color(255, 204, 0));
        cancelarBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelarBTN.setText("Cancelar");
        cancelarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(folioLabel)
                        .addGap(366, 366, 366)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrePruebaLabel)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1051, Short.MAX_VALUE)
                        .addComponent(registrarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(folioLabel)
                    .addComponent(jLabel3)
                    .addComponent(nombreClienteLabel)
                    .addComponent(jLabel4)
                    .addComponent(nombrePruebaLabel))
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTNActionPerformed
        ResultadosPanel panelResultado = new ResultadosPanel(panel, analisisNegocio,resultadoNegocio,parametroNegocio);
        panel.cambiarPanel(panelResultado);
    }//GEN-LAST:event_cancelarBTNActionPerformed

    private void registrarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBTNActionPerformed
        this.guardarResultados();
        ResultadosPanel panelResultado = new ResultadosPanel(panel, analisisNegocio,resultadoNegocio,parametroNegocio);
        panel.cambiarPanel(panelResultado);
    }//GEN-LAST:event_registrarBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaResultados;
    private javax.swing.JButton cancelarBTN;
    private javax.swing.JLabel folioLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreClienteLabel;
    private javax.swing.JLabel nombrePruebaLabel;
    private javax.swing.JButton registrarBTN;
    // End of variables declaration//GEN-END:variables
}
